zstyle :plugin:fast-syntax-highlighting theme "tokyodark"
typeset -g FAST_THEME_NAME="tokyodark"
: ${FAST_HIGHLIGHT_STYLES[tokyodarkdefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkunknown-token]:=none}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkreserved-word]:=fg=#BB9AF7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkalias]:=fg=#7AA2F7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarksuffix-alias]:=fg=#7AA2F7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkbuiltin]:=fg=#7AA2F7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkfunction]:=fg=#7AA2F7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkcommand]:=fg=#7AA2F7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkprecommand]:=fg=#7AA2F7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkcommandseparator]:=fg=#d4d4d4}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkhashed-command]:=fg=#7AA2F7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkpath]:=fg=#BB9AF7,underline}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkpath_pathseparator]:=fg=#d4d4d4}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkglobbing]:=fg=#E5C07B}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkglobbing-ext]:=fg=#E5C07B}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkhistory-expansion]:=fg=#D19A66}
: ${FAST_HIGHLIGHT_STYLES[tokyodarksingle-hyphen-option]:=fg=#c0caf5}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkdouble-hyphen-option]:=fg=#c0caf5}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkback-quoted-argument]:=fg=#ACCFD7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarksingle-quoted-argument]:=fg=#F7768E}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkdouble-quoted-argument]:=fg=#F7768E}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkdollar-quoted-argument]:=fg=#F7768E}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkback-or-dollar-double-quoted-argument]:=fg=#ACCFD7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkback-dollar-quoted-argument]:=fg=#ACCFD7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkredirection]:=fg=#d4d4d4}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkcomment]:=fg=#9ECE6A}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkvariable]:=fg=#ACCFD7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkmathvar]:=fg=#ACCFD7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkmathnum]:=fg=#b5cea8}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkmatherr]:=fg=#F7768E}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkassign-array-bracket]:=fg=#d4d4d4}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkfor-loop-variable]:=fg=#ACCFD7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkfor-loop-number]:=fg=#b5cea8}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkfor-loop-operator]:=fg=#BB9AF7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkfor-loop-separator]:=fg=#d4d4d4}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkexec-descriptor]:=fg=#7DCFFF}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkhere-string-tri]:=fg=#7DCFFF}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkhere-string-text]:=none}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkhere-string-var]:=fg=#ACCFD7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarksecondary]:=free}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkcase-input]:=fg=#7AA2F7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkcase-parentheses]:=fg=#d4d4d4}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkcase-condition]:=fg=#BB9AF7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkcorrect-subtle]:=fg=#9ECE6A}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkincorrect-subtle]:=fg=#F7768E}
: ${FAST_HIGHLIGHT_STYLES[tokyodarksubtle-separator]:=fg=#565f89}
: ${FAST_HIGHLIGHT_STYLES[tokyodarksubtle-bg]:=none}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkpath-to-dir]:=fg=#BB9AF7,underline}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkpaired-bracket]:=none}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkbracket-level-1]:=fg=#7AA2F7,bold}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkbracket-level-2]:=fg=#BB9AF7,bold}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkbracket-level-3]:=fg=#E5C07B,bold}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkglobal-alias]:=fg=#7AA2F7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarksubcommand]:=fg=#BB9AF7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarksingle-sq-bracket]:=fg=#7AA2F7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkdouble-sq-bracket]:=fg=#7AA2F7}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkdouble-paren]:=fg=#d4d4d4}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkoptarg-string]:=fg=#F7768E}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkoptarg-number]:=fg=#b5cea8}
: ${FAST_HIGHLIGHT_STYLES[tokyodarkrecursive-base]:=fg=#c0caf5}
