#!/usr/bin/env zsh
# config-map.zsh — single source of truth for collect/distribute. Sourced, not run.
# Record format: label|applies|type|repo_path|mac_live|linux_live   (applies: both|mac|linux)
# Use "-" for a live path that does not apply to that OS.

df_os() { [[ "$(uname)" == "Darwin" ]] && print -r -- mac || print -r -- linux }

typeset -ga DOTFILES_RECORDS=(
  # --- common entrypoints (pure includes) ---
  "zshrc|both|file|configs/common/zsh/zshrc|$HOME/.zshrc|$HOME/.zshrc"
  "ghostty|both|file|configs/common/ghostty/config|$HOME/Library/Application Support/com.mitchellh.ghostty/config|$HOME/.config/ghostty/config"
  "gitconfig|both|file|configs/common/git/gitconfig|$HOME/.gitconfig|$HOME/.gitconfig"
  # --- common fragments / single files ---
  "zsh-common|both|file|configs/common/zsh/common.zsh|$HOME/.config/zsh/common.zsh|$HOME/.config/zsh/common.zsh"
  "ghostty-base|both|file|configs/common/ghostty/config-base|$HOME/Library/Application Support/com.mitchellh.ghostty/config-base|$HOME/.config/ghostty/config-base"
  "git-common|both|file|configs/common/git/common.gitconfig|$HOME/.config/git/common.gitconfig|$HOME/.config/git/common.gitconfig"
  "starship|both|file|configs/common/starship/starship.toml|$HOME/.config/starship.toml|$HOME/.config/starship.toml"
  # fsh: track only the theme SOURCE (tokyodark.ini); the generated current_theme.zsh /
  # *.zwc caches are regenerated by `fast-theme XDG:tokyodark` (run once at setup).
  "fsh|both|file|configs/common/fsh/tokyodark.ini|$HOME/.config/fsh/tokyodark.ini|$HOME/.config/fsh/tokyodark.ini"
  "nvim|both|dir|configs/common/nvim|$HOME/.config/nvim|$HOME/.config/nvim"
  # --- os fragments ---
  "zsh-os|mac|file|configs/macos/zsh/os.zsh|$HOME/.config/zsh/os.zsh|-"
  "zsh-os|linux|file|configs/linux/zsh/os.zsh|-|$HOME/.config/zsh/os.zsh"
  "ghostty-os|mac|file|configs/macos/ghostty/config-os|$HOME/Library/Application Support/com.mitchellh.ghostty/config-os|-"
  "ghostty-os|linux|file|configs/linux/ghostty/config-os|-|$HOME/.config/ghostty/config-os"
  # (git signing identity is per-machine/untracked at ~/.config/git/signing.local — NOT distributed)
  # --- mac-only ---
  "karabiner|mac|file|configs/macos/karabiner/karabiner.json|$HOME/.config/karabiner/karabiner.json|-"
  "aerospace|mac|file|configs/macos/aerospace/aerospace.toml|$HOME/.config/aerospace/aerospace.toml|-"
  "alfred|mac|dir|configs/macos/alfred/Alfred.alfredpreferences|$HOME/Library/Application Support/Alfred/Alfred.alfredpreferences|-"
  # --- linux-only ---
  "xremap|linux|file|configs/linux/xremap/config.yml|-|$HOME/.config/xremap/config.yml"
  "hypr|linux|file|configs/linux/hypr/hyprland.conf|-|$HOME/.config/hypr/hyprland.conf"
  "environmentd|linux|file|configs/linux/environment.d/ssh-agent.conf|-|$HOME/.config/environment.d/ssh-agent.conf"
  "wallpaper|linux|file|configs/linux/wallpapers/tokyonight.jpg|-|$HOME/Pictures/Wallpapers/tokyonight.jpg"
  # --- ricing: theme source + generator (generated color fragments are derived, not tracked) ---
  "theme-palette|linux|file|configs/linux/theme/tokyonight.conf|-|$HOME/.config/theme/tokyonight.conf"
  # --- waybar ---
  "waybar-config|linux|file|configs/linux/waybar/config.jsonc|-|$HOME/.config/waybar/config.jsonc"
  "waybar-modules|linux|file|configs/linux/waybar/modules-custom.jsonc|-|$HOME/.config/waybar/modules-custom.jsonc"
  "waybar-style|linux|file|configs/linux/waybar/style.css|-|$HOME/.config/waybar/style.css"
  "waybar-scripts|linux|dir|configs/linux/waybar/scripts|-|$HOME/.config/waybar/scripts"
  "waybar-bt-rename|linux|file|configs/linux/waybar/bluetooth-rename.conf|-|$HOME/.config/waybar/bluetooth-rename.conf"
  "hyprlock|linux|file|configs/linux/hypr/hyprlock.conf|-|$HOME/.config/hypr/hyprlock.conf"
  "wlogout-layout|linux|file|configs/linux/wlogout/layout|-|$HOME/.config/wlogout/layout"
  "wlogout-style|linux|file|configs/linux/wlogout/style.css|-|$HOME/.config/wlogout/style.css"
  "swaync-config|linux|file|configs/linux/swaync/config.json|-|$HOME/.config/swaync/config.json"
  "swaync-style|linux|file|configs/linux/swaync/style.css|-|$HOME/.config/swaync/style.css"
)

# df_each <callback>: calls `callback label type repo_path live_path` for every record
# that applies to the current OS (skips records whose live path for this OS is "-").
df_each() {
  local cb="$1" os; os="$(df_os)"
  local rec label applies type repo mac_live linux_live live
  for rec in "${DOTFILES_RECORDS[@]}"; do
    IFS='|' read -r label applies type repo mac_live linux_live <<< "$rec"
    [[ "$applies" == "both" || "$applies" == "$os" ]] || continue
    [[ "$os" == "mac" ]] && live="$mac_live" || live="$linux_live"
    [[ "$live" == "-" ]] && continue
    "$cb" "$label" "$type" "$repo" "$live"
  done
}
