#!/usr/bin/env zsh
# config-map.zsh — single source of truth for the deploy scripts. Sourced, not run.
#
# Record format: label|applies|type|repo_path|mac_live|linux_live|mode
#   applies : both | mac | linux
#   type    : file | dir
#   mode    : link (default, may be omitted) | copy
#   "-"     : this live path does not apply to that OS
#
# LINK is the default. COPY is only for apps that save by writing a temp file and
# renaming it over the target, which replaces the symlink with a regular file and
# silently detaches the config from the repo — Alfred's bundle is the known case.

df_os() { [[ "$(uname)" == "Darwin" ]] && print -r -- mac || print -r -- linux }

typeset -ga DOTFILES_RECORDS=(
  # --- common entrypoints (pure includes) ---
  "zshrc|both|file|configs/common/zsh/zshrc|$HOME/.zshrc|$HOME/.zshrc"
  "ghostty|both|file|configs/common/ghostty/config|$HOME/Library/Application Support/com.mitchellh.ghostty/config|$HOME/.config/ghostty/config"
  # --- common fragments / single files ---
  "zsh-common|both|file|configs/common/zsh/common.zsh|$HOME/.config/zsh/common.zsh|$HOME/.config/zsh/common.zsh"
  "ghostty-base|both|file|configs/common/ghostty/config-base|$HOME/Library/Application Support/com.mitchellh.ghostty/config-base|$HOME/.config/ghostty/config-base"
  # ~/.gitconfig is NOT deployed: it is the untracked per-machine file (setup.sh creates it).
  "gitconfig|both|file|configs/common/git/gitconfig|$HOME/.config/git/config|$HOME/.config/git/config"
  "starship|both|file|configs/common/starship/starship.toml|$HOME/.config/starship.toml|$HOME/.config/starship.toml"
  # fsh: track only the theme SOURCE (tokyodark.ini); the generated current_theme.zsh /
  # *.zwc caches are regenerated by `fast-theme XDG:tokyodark` (run once at setup).
  "fsh|both|file|configs/common/fsh/tokyodark.ini|$HOME/.config/fsh/tokyodark.ini|$HOME/.config/fsh/tokyodark.ini"
  # linked, so the plugin manager's lazy-lock.json lands in the repo (tracked, wanted)
  "nvim|both|dir|configs/common/nvim|$HOME/.config/nvim|$HOME/.config/nvim"
  # --- os fragments ---
  "zsh-os|mac|file|configs/macos/zsh/os.zsh|$HOME/.config/zsh/os.zsh|-"
  "zsh-os|linux|file|configs/linux/zsh/os.zsh|-|$HOME/.config/zsh/os.zsh"
  "ghostty-os|mac|file|configs/macos/ghostty/config-os|$HOME/Library/Application Support/com.mitchellh.ghostty/config-os|-"
  "ghostty-os|linux|file|configs/linux/ghostty/config-os|-|$HOME/.config/ghostty/config-os"
  # --- mac-only ---
  "karabiner|mac|file|configs/macos/karabiner/karabiner.json|$HOME/.config/karabiner/karabiner.json|-"
  "aerospace|mac|file|configs/macos/aerospace/aerospace.toml|$HOME/.config/aerospace/aerospace.toml|-"
  # COPY: Alfred rewrites this bundle wholesale. The only record collect still needs.
  "alfred|mac|dir|configs/macos/alfred/Alfred.alfredpreferences|$HOME/Library/Application Support/Alfred/Alfred.alfredpreferences|-|copy"
  # --- linux-only ---
  "xremap|linux|file|configs/linux/xremap/config.yml|-|$HOME/.config/xremap/config.yml"
  # --- ricing: master palette + one dir per app ---
  #   theme-apply's fragments land in the repo for dir records (gitignored) and stay
  #   live-only for file records.
  "theme-palette|linux|file|configs/linux/theme/tokyonight.conf|-|$HOME/.config/theme/tokyonight.conf"
  "hypr|linux|dir|configs/linux/hypr|-|$HOME/.config/hypr"
  "waybar|linux|dir|configs/linux/waybar|-|$HOME/.config/waybar"
  # FILE records so their generated colour fragments never enter the repo
  "fuzzel|linux|file|configs/linux/fuzzel/fuzzel.ini|-|$HOME/.config/fuzzel/fuzzel.ini"
  "mako|linux|file|configs/linux/mako/config|-|$HOME/.config/mako/config"
  "wlogout|linux|dir|configs/linux/wlogout|-|$HOME/.config/wlogout"
)

# df_each <callback>: calls `callback label type repo_path live_path mode` for every
# record that applies to the current OS (skips records whose live path here is "-").
df_each() {
  local cb="$1" os; os="$(df_os)"
  local rec label applies type repo mac_live linux_live mode live
  for rec in "${DOTFILES_RECORDS[@]}"; do
    IFS='|' read -r label applies type repo mac_live linux_live mode <<< "$rec"
    [[ "$applies" == "both" || "$applies" == "$os" ]] || continue
    [[ "$os" == "mac" ]] && live="$mac_live" || live="$linux_live"
    [[ "$live" == "-" ]] && continue
    "$cb" "$label" "$type" "$repo" "$live" "${mode:-link}"
  done
}
