#!/usr/bin/env zsh
# config-map.zsh — single source of truth for the deploy scripts. Sourced, not run.
#
# Record format: label|applies|type|repo_path|mac_live|linux_live|mode
#   applies : both | mac | linux
#   type    : file | dir
#   mode    : link (default, may be omitted) | copy
#   "-"     : this live path does not apply to that OS
#
# LINK is the default and should stay that way: the live path becomes a symlink into
# the repo, so there is exactly one copy of every config and editing the repo is
# instant. COPY exists only for apps that save by writing a temp file and renaming it
# over the target — that REPLACES the symlink with a regular file, silently detaching
# the config from the repo. Alfred's preferences bundle is the known case.
#
# Generated files (theme-apply's colour fragments) now land inside the repo, next to
# the tracked config they belong to, and are excluded by .gitignore instead of by the
# old DOTFILES_DIR_EXCLUDES rsync machinery.

df_os() { [[ "$(uname)" == "Darwin" ]] && print -r -- mac || print -r -- linux }

typeset -ga DOTFILES_RECORDS=(
  # --- common entrypoints (pure includes) ---
  "zshrc|both|file|configs/common/zsh/zshrc|$HOME/.zshrc|$HOME/.zshrc"
  "ghostty|both|file|configs/common/ghostty/config|$HOME/Library/Application Support/com.mitchellh.ghostty/config|$HOME/.config/ghostty/config"
  "gitconfig|both|file|configs/common/git/gitconfig|$HOME/.gitconfig|$HOME/.gitconfig"
  # --- common fragments / single files ---
  "zsh-common|both|file|configs/common/zsh/common.zsh|$HOME/.config/zsh/common.zsh|$HOME/.config/zsh/common.zsh"
  "ghostty-base|both|file|configs/common/ghostty/config-base|$HOME/Library/Application Support/com.mitchellh.ghostty/config-base|$HOME/.config/ghostty/config-base"
  "git-common|both|file|configs/common/git/common.gitconfig|$HOME/.config/git/common.gitconfig|$HOME/.config/git/common.gitconfig"
  "starship|both|file|configs/common/starship/starship.toml|$HOME/.config/starship.toml|$HOME/.config/starship.toml"
  # fsh: track only the theme SOURCE (tokyodark.ini); the generated current_theme.zsh /
  # *.zwc caches are regenerated by `fast-theme XDG:tokyodark` (run once at setup).
  "fsh|both|file|configs/common/fsh/tokyodark.ini|$HOME/.config/fsh/tokyodark.ini|$HOME/.config/fsh/tokyodark.ini"
  # nvim: linked, so lazy-lock.json written by the plugin manager lands in the repo —
  # which is what we want; it is tracked and should move with the config.
  "nvim|both|dir|configs/common/nvim|$HOME/.config/nvim|$HOME/.config/nvim"
  # --- os fragments ---
  "zsh-os|mac|file|configs/macos/zsh/os.zsh|$HOME/.config/zsh/os.zsh|-"
  "zsh-os|linux|file|configs/linux/zsh/os.zsh|-|$HOME/.config/zsh/os.zsh"
  "ghostty-os|mac|file|configs/macos/ghostty/config-os|$HOME/Library/Application Support/com.mitchellh.ghostty/config-os|-"
  "ghostty-os|linux|file|configs/linux/ghostty/config-os|-|$HOME/.config/ghostty/config-os"
  # (git signing identity is per-machine/untracked at ~/.config/git/signing.local — NOT deployed)
  # --- mac-only ---
  "karabiner|mac|file|configs/macos/karabiner/karabiner.json|$HOME/.config/karabiner/karabiner.json|-"
  "aerospace|mac|file|configs/macos/aerospace/aerospace.toml|$HOME/.config/aerospace/aerospace.toml|-"
  # alfred: COPY. Alfred rewrites this preferences bundle wholesale, which would replace
  # a symlink with a real directory. It is the one record that still needs collect.
  "alfred|mac|dir|configs/macos/alfred/Alfred.alfredpreferences|$HOME/Library/Application Support/Alfred/Alfred.alfredpreferences|-|copy"
  # --- linux-only ---
  "xremap|linux|file|configs/linux/xremap/config.yml|-|$HOME/.config/xremap/config.yml"
  "environmentd|linux|file|configs/linux/environment.d/ssh-agent.conf|-|$HOME/.config/environment.d/ssh-agent.conf"
  # --- ricing: master palette + one dir per app ---
  #   theme-apply generates colour fragments (colors.lua / colors.css /
  #   hyprlock-colors.conf / mako's colors) into these live dirs. Because the dirs are
  #   symlinks, those files land in the repo and are handled by .gitignore.
  "theme-palette|linux|file|configs/linux/theme/tokyonight.conf|-|$HOME/.config/theme/tokyonight.conf"
  "hypr|linux|dir|configs/linux/hypr|-|$HOME/.config/hypr"
  "waybar|linux|dir|configs/linux/waybar|-|$HOME/.config/waybar"
  "swaync|linux|dir|configs/linux/swaync|-|$HOME/.config/swaync"
  "wlogout|linux|dir|configs/linux/wlogout|-|$HOME/.config/wlogout"
  "vicinae|linux|dir|configs/linux/vicinae|-|$HOME/.config/vicinae"
  "vicinae-unit|linux|file|configs/linux/systemd/vicinae-override.conf|-|$HOME/.config/systemd/user/vicinae.service.d/override.conf"
)

# df_each <callback>: calls `callback label type repo_path live_path mode` for every
# record that applies to the current OS (skips records whose live path here is "-").
df_each() {
  local cb="$1" os; os="$(df_os)"
  local rec label applies type repo mac_live linux_live mode live
  for rec in "${DOTFILES_RECORDS[@]}"; do
    IFS='|' read -r label applies type repo mac_live linux_live mode <<< "$rec"
    [[ "$applies" == "both" || "$applies" == "$os" ]] || continue
    [[ "$os" == "mac" ]] && live="$mac_live" || live="$linux_live"
    [[ "$live" == "-" ]] && continue
    "$cb" "$label" "$type" "$repo" "$live" "${mode:-link}"
  done
}
