-- Hyprland configuration (Lua format).
-- Ported from the legacy hyprland.conf: hyprlang `.conf` support is removed in
-- Hyprland 0.57. Section order and rationale below mirror the old file 1:1.

local home = os.getenv("HOME")

-- TokyoNight palette (generated by theme-apply; provides c.blue, c.purple, c.bg, etc.)
local c = require("colors")

-- Modifier: Caps Lock is now Mod3 (Hyper). The XKB rule below (caps:hyper) is what
-- turns the physical key into Mod3; xremap re-emits CapsLock so this applies to its
-- virtual keyboard too. MOD3 must be uppercase — the Lua key parser rejects "Mod3".
local hyper = "MOD3"

-- Nvidia-specific environment
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

-- SSH agent socket (Proton Pass desktop app). Set here so GUI apps launched by
-- Hyprland — and all terminals/git — see the same socket. Proton Pass serves the
-- git signing key from its vault while the vault is unlocked.
hl.env("SSH_AUTH_SOCK", home .. "/.ssh/proton-pass-ssh-agent.sock")

hl.config({
    -- Remap Caps Lock to Hyper
    input = {
        kb_layout    = "abc,no,ru",
        kb_options   = "caps:hyper,grp:shifts_toggle",
        follow_mouse = 0,
    },

    -- Accordion behavior: keep focus-cycling while a window is fullscreen, so
    -- Caps+F blows a tile up and Caps+h/j/k/l swaps through the rest, each
    -- staying fullscreen — like aerospace's accordion.
    binds = {
        movefocus_cycles_fullscreen = true,
    },

    -- Restrained, mac-like looks. Colors from the required colors module.
    -- (rounding lives under decoration, not general, in this Hyprland version.)
    general = {
        gaps_in     = 4,
        gaps_out    = 8,
        border_size = 2,
        col = {
            active_border   = { colors = { c.blue, c.purple }, angle = 45 },
            inactive_border = c.bg_dark,
        },
    },

    decoration = {
        rounding = 0,
        blur = {
            enabled = true,
            size    = 4,
            passes  = 2,
        },
        -- Inactive-window dimming so focus pops (mirrors terminal-opacity restraint).
        dim_inactive = true,
        dim_strength = 0.12,
    },

    -- Input/focus: stop cursor warping to newly focused tile; focus changes only on click.
    cursor = {
        no_warps = true,
    },

    misc = {
        -- hyprland-guiutils is not packaged in the ashbuk/Hyprland-Fedora COPR we
        -- install from, and it is only a soft runtime dep (optional Qt dialogs:
        -- config-error popup, update/donate screens). Silence the startup nag.
        disable_hyprland_guiutils_check = true,
    },

    animations = {
        enabled = true,
    },
})

-- Instant workspace switching preserved; other animations get snappy easing.
hl.curve("snappy", { type = "bezier", points = { { 0.22, 1 }, { 0.36, 1 } } })  -- easeOutQuint-ish
hl.animation({ leaf = "workspaces", enabled = false })                           -- KEEP INSTANT
hl.animation({ leaf = "windows",    enabled = true, speed = 3, bezier = "snappy", style = "popin 6%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "snappy", style = "popin 6%" })
hl.animation({ leaf = "fade",       enabled = true, speed = 3, bezier = "snappy" })
hl.animation({ leaf = "border",     enabled = true, speed = 4, bezier = "snappy" })

-- Focus — Caps + h/j/k/l
hl.bind(hyper .. " + h", hl.dsp.focus({ direction = "l" }))
hl.bind(hyper .. " + l", hl.dsp.focus({ direction = "r" }))
hl.bind(hyper .. " + k", hl.dsp.focus({ direction = "u" }))
hl.bind(hyper .. " + j", hl.dsp.focus({ direction = "d" }))

-- Move window — Caps + Super + h/j/k/l
-- group_aware = like a plain move, but pushing a window into a group MERGES
-- it in (so you can collect already-open tiles into a group; see Caps+, below).
-- This is the legacy `movewindoworgroup` dispatcher. Verified by A/B test: without
-- group_aware the two windows merely swap places; with it they merge into one group.
hl.bind(hyper .. " + SUPER + h", hl.dsp.window.move({ direction = "l", group_aware = true }))
hl.bind(hyper .. " + SUPER + l", hl.dsp.window.move({ direction = "r", group_aware = true }))
hl.bind(hyper .. " + SUPER + k", hl.dsp.window.move({ direction = "u", group_aware = true }))
hl.bind(hyper .. " + SUPER + j", hl.dsp.window.move({ direction = "d", group_aware = true }))

-- Workspaces — Caps + 1-9, and move window to workspace — Caps + Super + 1-9
--
-- The legacy `movetoworkspacesilent` has NO direct Lua equivalent. `silent` is not a
-- recognised key on hl.dsp.window.move, and unrecognised keys are dropped without any
-- error whenever a valid key (here `workspace`) is present — so the naive translation
-- silently degrades to `movetoworkspace` and drags the view along with the window.
-- Restore the previously active workspace immediately after the move instead.
local function move_to_workspace_silent(n)
    return function()
        local cur = hl.get_active_workspace().id
        hl.dispatch(hl.dsp.window.move({ workspace = n }))
        hl.dispatch(hl.dsp.focus({ workspace = cur }))
    end
end

for i = 1, 9 do
    hl.bind(hyper .. " + " .. i,         hl.dsp.focus({ workspace = i }))
    hl.bind(hyper .. " + SUPER + " .. i, move_to_workspace_silent(i))
end

-- App launcher — Super+Space. vicinae runs as a daemon (see autostart below), so
-- this only toggles an already-warm window. Fuzzy matching and frecency ranking are
-- vicinae's own; file/folder search is indexed in the background.
hl.bind("SUPER + Space", hl.dsp.exec_cmd("vicinae toggle"))

-- Terminal — Hyper+Return
hl.bind(hyper .. " + Return", hl.dsp.exec_cmd("ghostty"))

-- Kill window — Super+Q (window), Super+W (mac "close": closes terminal windows;
-- in GUI apps xremap rewrites Super+W → Ctrl+W before this bind, so it = close tab there)
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + W", hl.dsp.window.close())

-- ── Layout / window state (Caps + key) — mirrors aerospace main mode ──────
hl.bind(hyper .. " + slash", hl.dsp.layout("togglesplit"))  -- flip dwindle split dir for next window
hl.bind(hyper .. " + comma", hl.dsp.group.toggle())         -- merge/dissolve a tabbed group (accordion-ish)
hl.bind(hyper .. " + F",     hl.dsp.window.fullscreen())    -- fullscreen (accordion: see movefocus cycling above)
hl.bind(hyper .. " + Space", hl.dsp.window.float({ action = "toggle" }))  -- float/unfloat (SUPER+Space is vicinae)

-- ── Quick resize (Caps + -/=) — single binds, no resize *mode* ───────────
hl.bind(hyper .. " + minus", hl.dsp.window.resize({ x = -50, y = -50, relative = true }))
hl.bind(hyper .. " + equal", hl.dsp.window.resize({ x = 50,  y = 50,  relative = true }))

-- ── Group tab cycling (Caps + [ / ]) — for group.toggle stacks ─────────────
hl.bind(hyper .. " + bracketleft",  hl.dsp.group.prev())
hl.bind(hyper .. " + bracketright", hl.dsp.group.next())
hl.bind(hyper .. " + SUPER + comma", hl.dsp.window.move({ out_of_group = true }))  -- pop focused window back out of its group

-- ── Monitors ──────────────────────────────────────────────────────────────
hl.bind(hyper .. " + grave", hl.dsp.workspace.move({ monitor = "+1" }))  -- move workspace to next monitor

-- ── macOS-style app shortcuts that collide with Caps+Super window mgmt ──
-- These live here (not xremap) so the compositor can tell Super+key apart from
-- Caps+Super+key (Hyper+Super). send_shortcut forwards Ctrl+key to the focused app.
--   Super+L      → Ctrl+L  (focus address bar / clear in terminal)
--   Super+1..9   → Ctrl+1..9 (browser tab switching)
hl.bind("SUPER + L", hl.dsp.send_shortcut({ mods = "CTRL", key = "L", window = "activewindow" }))
-- Tab switching → Ctrl+1..9.  ⚠️ BROWSER-DEPENDENT: Brave/Chromium use Ctrl+number.
-- Firefox uses Alt+number instead — switch CTRL→ALT if you ever go back to it.
for i = 1, 9 do
    hl.bind("SUPER + " .. i, hl.dsp.send_shortcut({ mods = "CTRL", key = tostring(i), window = "activewindow" }))
end

-- power menu (Caps+Super+Esc)
hl.bind(hyper .. " + SUPER + Escape", hl.dsp.exec_cmd(
    "wlogout -p layer-shell -b 2 -l " .. home .. "/.config/wlogout/layout -C " .. home .. "/.config/wlogout/style.css"))

-- ── Screenshots (grim+slurp+swappy) — mac-style binds, save + clipboard ──
local ssdir = home .. "/Pictures/Screenshots"
hl.bind("SUPER + SHIFT + 4", hl.dsp.exec_cmd(
    "mkdir -p " .. ssdir .. ' && f="' .. ssdir .. '/$(date +%Y-%m-%d_%H-%M-%S).png" && grim -g "$(slurp)" "$f" && wl-copy < "$f" && swappy -f "$f"'))
hl.bind("SUPER + SHIFT + 3", hl.dsp.exec_cmd(
    "mkdir -p " .. ssdir .. ' && f="' .. ssdir .. '/$(date +%Y-%m-%d_%H-%M-%S).png" && grim "$f" && wl-copy < "$f"'))

-- vicinae runs as a REGULAR window (layer_shell is off in its settings.json, so that
-- xremap can see its class and apply the mac-style Super->Ctrl remaps inside it).
-- That means blur comes from a windowrule, not a layerrule: Hyprland only blurs behind
-- a window that is actually translucent, so the opacity here is what switches blur on.
hl.window_rule({
    name    = "vicinae-look",
    match   = { class = "vicinae" },
    opacity = 0.90,
})

-- Autostart
-- xremap as a Hyprland child: inherits HYPRLAND_INSTANCE_SIGNATURE + WAYLAND_DISPLAY
-- so its app-aware (terminal-excluded) remapping works, and it's live the moment
-- the session starts — no systemd graphical-session.target needed. --watch handles
-- the Bluetooth keyboard re-appearing as a new device on reconnect.
--
-- vicinae launcher daemon. Started via systemd (not `vicinae server` directly) so it keeps
-- Restart=always and journalctl logging, and so the tracked drop-in override at
-- ~/.config/systemd/user/vicinae.service.d/override.conf applies (it adds
-- --no-extension-runtime, which kills the bundled node process). It cannot simply be
-- `systemctl --user enable`d: the unit is WantedBy=graphical-session.target, and that
-- target never activates in this no-uwsm session — same reason xremap is an exec-once.
hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/local/bin/xremap --watch=config,device " .. home .. "/.config/xremap/config.yml")
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("swaybg -i " .. home .. "/Pictures/Wallpapers/tokyonight.jpg -m fill")
    hl.exec_cmd("/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1")
    hl.exec_cmd("systemctl --user start vicinae")
end)
