-- Hyprland configuration. Rationale for the non-obvious choices lives in
-- packages/linux-packages.md under "Desktop notes".

local home = os.getenv("HOME")

local c = require("colors")   -- generated by theme-apply; hard error if missing
local hyper = "MOD3"          -- Caps Lock, via kb_options caps:hyper. Must be uppercase.

-- Nvidia-specific environment
hl.env("LIBVA_DRIVER_NAME", "nvidia")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("GBM_BACKEND", "nvidia-drm")
hl.env("__GLX_VENDOR_LIBRARY_NAME", "nvidia")
hl.env("NVD_BACKEND", "direct")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "wayland")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")

-- Proton Pass SSH agent, so GUI apps Hyprland launches see the same socket as shells.
hl.env("SSH_AUTH_SOCK", home .. "/.ssh/proton-pass-ssh-agent.sock")

hl.config({
    -- Remap Caps Lock to Hyper
    input = {
        kb_layout    = "abc,no,ru",
        kb_options   = "caps:hyper,grp:shifts_toggle",
        follow_mouse = 0,
    },

    binds = {   -- accordion: focus-cycling keeps working while fullscreen
        movefocus_cycles_fullscreen = true,
    },

    general = {   -- note: rounding lives under decoration, not here
        gaps_in     = 4,
        gaps_out    = 8,
        border_size = 2,
        col = {
            active_border   = { colors = { c.blue, c.purple }, angle = 45 },
            inactive_border = c.bg_dark,
        },
    },

    decoration = {
        rounding = 0,
        blur = {
            enabled = true,
            size    = 4,
            passes  = 2,
        },
        dim_inactive = true,   -- focus pops
        dim_strength = 0.12,
    },

    cursor = {   -- no cursor warp to the newly focused tile
        no_warps = true,
    },

    misc = {
        disable_hyprland_guiutils_check = true,   -- unpackaged on Fedora; drop this on Arch
    },

    animations = {
        enabled = true,
    },
})

-- Instant workspace switching preserved; other animations get snappy easing.
hl.curve("snappy", { type = "bezier", points = { { 0.22, 1 }, { 0.36, 1 } } })  -- easeOutQuint-ish
hl.animation({ leaf = "workspaces", enabled = false })                           -- KEEP INSTANT
hl.animation({ leaf = "windows",    enabled = true, speed = 3, bezier = "snappy", style = "popin 6%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 3, bezier = "snappy", style = "popin 6%" })
hl.animation({ leaf = "fade",       enabled = true, speed = 3, bezier = "snappy" })
hl.animation({ leaf = "border",     enabled = true, speed = 4, bezier = "snappy" })

-- Focus — Caps + h/j/k/l
hl.bind(hyper .. " + h", hl.dsp.focus({ direction = "l" }))
hl.bind(hyper .. " + l", hl.dsp.focus({ direction = "r" }))
hl.bind(hyper .. " + k", hl.dsp.focus({ direction = "u" }))
hl.bind(hyper .. " + j", hl.dsp.focus({ direction = "d" }))

-- Move window — Caps + Super + h/j/k/l. group_aware merges into a group rather than swapping.
hl.bind(hyper .. " + SUPER + h", hl.dsp.window.move({ direction = "l", group_aware = true }))
hl.bind(hyper .. " + SUPER + l", hl.dsp.window.move({ direction = "r", group_aware = true }))
hl.bind(hyper .. " + SUPER + k", hl.dsp.window.move({ direction = "u", group_aware = true }))
hl.bind(hyper .. " + SUPER + j", hl.dsp.window.move({ direction = "d", group_aware = true }))

-- Workspaces — Caps + 1-9; move window there — Caps + Super + 1-9.
-- `silent` has no Lua equivalent, so re-focus the previous workspace after the move.
local function move_to_workspace_silent(n)
    return function()
        local cur = hl.get_active_workspace().id
        hl.dispatch(hl.dsp.window.move({ workspace = n }))
        hl.dispatch(hl.dsp.focus({ workspace = cur }))
    end
end

for i = 1, 9 do
    hl.bind(hyper .. " + " .. i,         hl.dsp.focus({ workspace = i }))
    hl.bind(hyper .. " + SUPER + " .. i, move_to_workspace_silent(i))
end

-- App launcher — Super+Space. Also the dmenu front-end for the fz-* wrappers.
hl.bind("SUPER + Space", hl.dsp.exec_cmd("fuzzel"))

-- Terminal — Hyper+Return
hl.bind(hyper .. " + Return", hl.dsp.exec_cmd("ghostty"))

-- Kill window. Super+W is mac "close": xremap rewrites it to Ctrl+W in GUI apps first.
hl.bind("SUPER + Q", hl.dsp.window.close())
hl.bind("SUPER + W", hl.dsp.window.close())

-- ── Layout / window state (Caps + key) — mirrors aerospace main mode ──────
hl.bind(hyper .. " + slash", hl.dsp.layout("togglesplit"))  -- flip dwindle split dir for next window
hl.bind(hyper .. " + comma", hl.dsp.group.toggle())         -- merge/dissolve a tabbed group (accordion-ish)
hl.bind(hyper .. " + F",     hl.dsp.window.fullscreen())    -- fullscreen (accordion: see movefocus cycling above)
hl.bind(hyper .. " + Space", hl.dsp.window.float({ action = "toggle" }))  -- float/unfloat (SUPER+Space is the launcher)

-- ── Quick resize (Caps + -/=) — single binds, no resize *mode* ───────────
hl.bind(hyper .. " + minus", hl.dsp.window.resize({ x = -50, y = -50, relative = true }))
hl.bind(hyper .. " + equal", hl.dsp.window.resize({ x = 50,  y = 50,  relative = true }))

-- ── Group tab cycling (Caps + [ / ]) — for group.toggle stacks ─────────────
hl.bind(hyper .. " + bracketleft",  hl.dsp.group.prev())
hl.bind(hyper .. " + bracketright", hl.dsp.group.next())
hl.bind(hyper .. " + SUPER + comma", hl.dsp.window.move({ out_of_group = true }))  -- pop focused window back out of its group

-- ── Monitors ──────────────────────────────────────────────────────────────
hl.bind(hyper .. " + grave", hl.dsp.workspace.move({ monitor = "+1" }))  -- move workspace to next monitor

-- ── macOS app shortcuts that collide with Caps+Super window mgmt ─────────
-- Here, not xremap, so the compositor can tell Super+key from Caps+Super+key.
hl.bind("SUPER + L", hl.dsp.send_shortcut({ mods = "CTRL", key = "L", window = "activewindow" }))
-- Tab switching. ⚠ Brave/Chromium use Ctrl+number; Firefox needs ALT instead.
for i = 1, 9 do
    hl.bind("SUPER + " .. i, hl.dsp.send_shortcut({ mods = "CTRL", key = tostring(i), window = "activewindow" }))
end

-- power menu (Caps+Super+Esc)
hl.bind(hyper .. " + SUPER + Escape", hl.dsp.exec_cmd(
    "wlogout -p layer-shell -b 2 -l " .. home .. "/.config/wlogout/layout -C " .. home .. "/.config/wlogout/style.css"))

-- ── Screenshots (grim+slurp+swappy) — mac-style binds, save + clipboard ──
local ssdir = home .. "/Pictures/Screenshots"
hl.bind("SUPER + SHIFT + 4", hl.dsp.exec_cmd(
    "mkdir -p " .. ssdir .. ' && f="' .. ssdir .. '/$(date +%Y-%m-%d_%H-%M-%S).png" && grim -g "$(slurp)" "$f" && wl-copy < "$f" && swappy -f "$f"'))
hl.bind("SUPER + SHIFT + 3", hl.dsp.exec_cmd(
    "mkdir -p " .. ssdir .. ' && f="' .. ssdir .. '/$(date +%Y-%m-%d_%H-%M-%S).png" && grim "$f" && wl-copy < "$f"'))

-- fuzzel is layer-shell, so blur is a layer rule. Namespace is set in fuzzel.ini.
hl.layer_rule({
    name  = "fuzzel-blur",
    match = { namespace = "fuzzel" },
    blur  = true,
})

-- Autostart. xremap must be a Hyprland child to inherit the instance signature.
hl.on("hyprland.start", function()
    -- Resolved at runtime: Fedora installs the binary by hand to /usr/local/bin, Arch's
    -- package puts it in /usr/bin, and Hyprland's exec PATH does not reliably cover both.
    hl.exec_cmd("sh -c 'command -v xremap >/dev/null && X=xremap || X=/usr/local/bin/xremap; " ..
                "exec \"$X\" --watch=config,device " .. home .. "/.config/xremap/config.yml'")
    hl.exec_cmd("waybar")
    hl.exec_cmd("mako")
    hl.exec_cmd(home .. "/.local/bin/wallpaper-init")   -- image, or a solid palette colour
    -- First agent that exists wins. hyprpolkitagent is the Arch/first-party one; the
    -- rest are distro-dependent paths. NOTE: none of these is currently installed on
    -- this Fedora box, so there is no polkit agent running -- install one.
    hl.exec_cmd("sh -c 'for a in hyprpolkitagent " ..
                "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 " ..
                "/usr/libexec/polkit-gnome-authentication-agent-1 " ..
                "/usr/libexec/polkit-kde-authentication-agent-1; do " ..
                "command -v \"$a\" >/dev/null && exec \"$a\"; done'")
end)
